# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0007_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(max_length=20)),
                ('vin', models.CharField(max_length=40)),
                ('apk_valid_until', models.DateField()),
                ('brand', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('insured', models.BooleanField(default=True)),
                ('insurance_company', models.CharField(max_length=40)),
                ('insurance_valid_until', models.DateField()),
                ('duplicates', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('organization', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Vehicle')),
            ],
        ),
    ]
