# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20160309_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default='Onbekend', max_length=40),
        ),
    ]
