# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriversLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('authority', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=5)),
                ('valid_until', models.DateField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('bsn', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='driverslicense',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person'),
        ),
    ]
