# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_person_initials'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangerClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danger', models.CharField(choices=[('1', 'Vuurwapengevaarlijk'), ('2', 'Verzetpleger'), ('3', 'Harddrugs gebruiker'), ('4', 'Alcoholist'), ('5', 'Vluchtgevaarlijk'), ('6', 'Medische indicatie'), ('7', 'Zelfmoord neigingen'), ('8', 'Psychiatrisch patient')], max_length=2)),
                ('since', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dangerclasses', to='persons.Person')),
            ],
        ),
        migrations.AlterField(
            model_name='driverslicense',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driverslicenses', to='persons.Person'),
        ),
    ]
