# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20160306_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dangerclass',
            name='person',
        ),
        migrations.RemoveField(
            model_name='dangerclass',
            name='since',
        ),
        migrations.AddField(
            model_name='person',
            name='dangers',
            field=models.ManyToManyField(to='persons.DangerClass'),
        ),
    ]
