# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_auto_20160307_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('mk', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='persons.Person')),
            ],
        ),
    ]
