# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('organization', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('register', models.CharField(max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='persons.Person')),
            ],
        ),
    ]
