# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0009_auto_20160309_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='form',
            field=models.FileField(blank=True, null=True, upload_to='forms/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='dangers',
            field=models.ManyToManyField(blank=True, to='persons.DangerClass'),
        ),
    ]
