# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0010_auto_20160314_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='form',
        ),
    ]
