# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0011_remove_registration_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='form',
            field=models.URLField(blank=True, null=True),
        ),
    ]
